[pytest]
markers = smoke: testing critical functionalities.
          functional: testing all functionalities.
          integration: testing the data changes/ data flow.
          system: end to end testing
          tollywood: telugu film industry.